name: Google Cloud Destroy

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Run ID from the build workflow'
        required: true
        type: string

jobs:
  google-cloud-destroy-user-and-apis:
    runs-on: ubuntu-latest
    environment: google-cloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-user-apis
          run-id: ${{ inputs.build_run_id }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_email=${{ secrets.SERVICE_ACCOUNT_EMAIL }}" >> $GITHUB_ENV

      - name: Terraform init
        run: terraform init # -backend-config="bucket=${GCP_BUCKET_NAME}"
        working-directory: Terraform/user-and-apis

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: Terraform/user-and-apis

      - name: Terraform destroy
        run: terraform destroy -auto-approve tfplan
        working-directory: Terraform/user-and-apis

  google-cloud-destroy-cluster:
    runs-on: ubuntu-latest
    environment: google-cloud
    needs: google-cloud-destroy-user-and-apis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-cluster
          run-id: ${{ inputs.build_run_id }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_email=${{ secrets.SERVICE_ACCOUNT_EMAIL }}" >> $GITHUB_ENV

      - name: Terraform init
        run: terraform init # -backend-config="bucket=${GCP_BUCKET_NAME}"
        working-directory: Terraform/cluster

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: Terraform/cluster

      - name: Terraform destroy
        run: terraform destroy -auto-approve tfplan
        working-directory: Terraform/cluster
