name: Terraform Build

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "${GOOGLE_CREDENTIALS}" > ${HOME}/GOOGLE_CREDENTIALS_KEY.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/GOOGLE_CREDENTIALS_KEY.json" >> $GITHUB_ENV

      - name: Terraform init
        run: |
          terraform init -backend-config="bucket=${TF_VAR_BUCKET_NAME}"
        working-directory: Terraform/Staging
        env:
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_BUCKET_NAME }}

      - name: Terraform plan
        run: |
          terraform plan
        working-directory: Terraform/Staging

      - name: Terraform apply
        run: |
          terraform apply -auto-approve -json tfplan
        working-directory: Terraform/Staging
