name: Terraform Build

on:
  workflow_dispatch:

jobs:
  terraform-build-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_GOOGLE_CREDENTIALS }}

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${GCP_BUCKET_NAME}" >> $GITHUB_ENV

      - name: Terraform init
        run: |
          terraform init -backend-config="bucket=${GCP_BUCKET_NAME}"
        working-directory: Terraform/Staging
        env:
          GCP_BUCKET_NAME: ${{ vars.GCP_BUCKET_NAME }}

      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
        working-directory: Terraform/Staging

      - name: Terraform apply
        run: |
          terraform apply -auto-approve tfplan
        working-directory: Terraform/Staging

  terraform-build-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_GOOGLE_CREDENTIALS }}

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${GCP_BUCKET_NAME}" >> $GITHUB_ENV

      - name: Terraform init
        run: |
          terraform init -backend-config="bucket=${GCP_BUCKET_NAME}"
        working-directory: Terraform/Production
        env:
          GCP_BUCKET_NAME: ${{ vars.GCP_BUCKET_NAME }}

      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
        working-directory: Terraform/Production

      - name: Terraform apply
        run: |
          terraform apply -auto-approve tfplan
        working-directory: Terraform/Production
