name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up ENV Variables
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.GCP_REGION }}
          GCP_PROJECT_NAME: ${{ vars.GCP_PROJECT_NAME }}
          GCP_BUCKET_NAME: ${{ vars.GCP_BUCKET_NAME }}
        run: |
          echo "TF_VAR_google_project_id=${GCP_PROJECT_ID}" >> $GITHUB_ENV
          echo "TF_VAR_region=${GCP_REGION}" >> $GITHUB_ENV
          echo "TF_VAR_project_name=${GCP_PROJECT_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${GCP_BUCKET_NAME}" >> $GITHUB_ENV

      - name: Terraform init
        run: |
          terraform init -backend-config="bucket=${TF_VAR_bucket_name}"
        working-directory: Terraform/Staging
        env:
          TF_VAR_bucket_name: ${{ vars.GCP_BUCKET_NAME }}

      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve
        working-directory: Terraform/Staging
